on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Tox

jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: tox